---
- hosts: all
  become: true
  vars:
  tasks:
   
    - name: Upgrade All Packages
      yum:
        name: '*'
        state: latest
        update_only: true

    - name: Is a Rebooted Needed?
      ansible.builtin.command: needs-restarting -r
      register: reg_reboot_required
      ignore_errors: true
      failed_when: false
      changed_when: reg_reboot_required.rc != 0
      notify:
          - Reboot Required
    
  handlers:
      - name: Reboot Required
        ansible.builtin.reboot:
            msg: "Reboot initiated by Ansible after Linux kernel update"
            reboot_timeout: 3600
            test_command: w
