---
- hosts: c7
  become: true
  vars:
  tasks:
   
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
        update_only: true

    - name: Check if an upgrade is required
      command: /usr/bin/needs-restarting -r
      register: reboot_required
         
    - name: Reboot system if kernel was updated
      reboot:
      when:
        - reboot_required.rc == 1
