---
- hosts: skybridge
  gather_facts: no
  become: true
  pre_tasks:
    - name: read/write
      raw: rpi-rw
    
  tasks:  
    - name: Reboot
      reboot:

    - name: Ping to verify connectivity
      ansible.builtin.ping:
