---
- hosts: jammy
  become: true
  tasks:
    - name: Update Cache
      ansible.builtin.apt:
        update_cache: yes
            
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
    
    - name: Check if a reboot is needed on all servers
      stat: path=/var/run/reboot-required
      register: reboot_required_file
    
    - name: Reboot if Kernel updated
      reboot:
        when: reboot_required_file.stat.exists
